title: My Website
description: A simple Jekyll website with navigation tabs
baseurl: ""
url: "https://www.ayameki.com"  # Change this to your domain
theme: minima

# Navigation menu (edit this part)
nav:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Videos
    url: /videos
